- modules/static/app/controllers/static.go
Getting the prefix from fixed parameters was overriding the absPath and
causing 404 on static files for modules (e.g. testrunner)
> Fix for static module files

- server.go
Bug introduced by #843. See its thread for more details.
The app can extend the deadline for each message received without Revel's help. A sane deadline of 24 hours is set by default for WS requests now.
> Adds debug code to reproduce websocket connection timeout issue

- server.go
Hi guys,
This is actually a critical feature that we need as we will sometimes have requests coming into us which are larger than the default 10 MB allowed size.
> Configurable max body request size

- results.go
Add an option for trimming the generated HTML, which will do the following:
* Remove all leading & trailing whitespace on every line
* Remove all empty lines
* Attempt to keep formatting inside < pre > < /pre > tags
This is fairly safe unless "white-space: pre;" is used in css for formatting. Since there is no way to detect that, you will have to keep trimming off in these cases.
> Add an option to trim whitespace from rendered HTML.

- router.go
- router_test.go
See issue #869 and initial PR #870.
To clarify @notzippy's bug description:
**expected**
`/foo/Hithere`
**actual**
`/foo/*something?something=Hithere`
> Fixes wildcard reverse routing logic and adds test

- controller.go
We need check `response.Status` in filter chain, but the current implementation doesn't set status except `NotFound`, `Forbidden` and `Todo` methods. I have added default statuses for other render methods.
> Add default http.Status code for render methods.

- router.go
App doesn't crash when it doesn't have any routes to serve, and the
returned error is discarded, not checked.This checks if the error is
not nil and crashes if it should because no routes means nothing to
do.
> Fixes router app start bug without routes.

- controller.go
#728 introduced "301 Permanent Redirect" for `Redirect` result. But the way we use `Redirect` method requires "302 Found" aka Moved Temporarily. This PR restores the status code we used before.
> Use "302 Found" HTTP code for redirect

- fakeapp_test.go
- testdata/app/views/footer.html
- testdata/app/views/header.html
- testdata/app/views/hotels/show.html
- testdata/conf/app.conf
- testdata/conf/routes
- testdata/public/js/sessvars.js
#855 revealed some problems with our fake app tests. Particularly, incorrect order of elements' initialization. This PR fixes broken tests.
There were two options: either to implement every of booking sample controllers + job module controller in out fake app. Or just move some booking sample's files to testdata directory and use them there. I have settle on the second option.
Now tests of revel/revel do not depend on revel/samples, only on revel/modules.
@brendensoares What else do we need for v0.12 release?
> Fix broken fake app tests

- template.go
This PR addresses https://github.com/revel/revel/pull/753#commitcomment-9943539 and #729.
Behaviour of `Template` method from #753 should not be affected.
* If we have `index.html` and `Index.html` only one of them will be registered as template. And the second one will be ignored.
* If we have `{define "test"}` and `{define "TEST"}` the first declaration will be used and the second one ignored.
* Both `c.RenderTemplate("app/index.html")` and `c.RenderTemplate('App/Index.html')` work no matter what register `app` dir and `index.html` file have.
The only change is a map of lower case names is generated once. The map is then used to find a real name of template (whatever register it has). Thus, number of iterations to find the template we need (on average) will be decreased.
> Optimize search of template names

- validators.go
- validators_test.go
Removes `len`in favor of `utf8.RuneCountInString` when calculating length of strings in validators.
````go
len("ルビー")                       // 9 (wrong value)
utf8.RuneCountInString("ルビー")    // 3 (ok)
```
(Retargeting #890 to develop branch)
> Makes validators work with UTF-8 strings

- i18n.go
- i18n_test.go
- skeleton/conf/app.conf.template
i18n message has default format when the message is missing in message files.
It was defined as constants value `??? %s ???`. 
But it should be changeable especially on the production environment.
This function will attempt to allow revel's users to change the format in the config file.
The new config option name is `i18n.unknown_format`.
> Added i18n setting for unknown message value format.

- controller.go
- i18n.go
- template.go
This allows users to override the Message function in revel with their
own. It defaults to the existing Message function, so there should be no
compatibility issues.
> i18n: Make Message Translation plugable

- http.go
`application/javascript` is an accepted MIME type for JavaScript and
JSON document, and it's more popular than `text/javascript`.
See http://www.iana.org/assignments/media-types/application/javascript.
> Add `application/javascript` to accepted headers

- revel.go
- server.go
- session.go
- skeleton/conf/app.conf.template
```bash
Started GET /topics at 2015-03-28T18:09:41+08:00 from 127.0.0.1:57816
[app.go:54] (0.72ms) SELECT  * FROM `users`  WHERE (`users`.deleted_at IS NULL OR `users`.deleted_at <= '0001-01-02') AND ((id = '13')) ORDER BY `users`.id ASC LIMIT 1
[pagination.go:19] (0.59ms) SELECT  count(*) FROM `topics`  WHERE (`topics`.deleted_at IS NULL OR `topics`.deleted_at <= '0001-01-02') AND ((rank >= 0)) ORDER BY last_active_mark desc, id desc
[topic.go:83] (1.97ms) SELECT  * FROM `topics`  WHERE (`topics`.deleted_at IS NULL OR `topics`.deleted_at <= '0001-01-02') AND ((rank >= 0)) ORDER BY last_active_mark desc, id desc LIMIT 20 OFFSET 0
[topic.go:83] (0.82ms) SELECT  * FROM `users`  WHERE (`users`.deleted_at IS NULL OR `users`.deleted_at <= '0001-01-02') AND ((`id` in ('8','13','14'))) …
```
> Request log

- server.go
This is a minimalist approach to somewhat solve #648, #553 and #549. It is minimally invasive and just moves around some code.
I'm looking for feedback on how this could be improved or generally if that's an approach worthy of merging :-)
An example of how this can be integrated into an app lives here: https://github.com/metafex/revel-modules/tree/master/server. Personally I'm running this in production now and don't have any problems with it yet.
The example server module depends on https://github.com/revel/cmd/pull/22 to generate the necessary code in the main function.
> Add InitServer function returning the http handler

- skeleton/conf/app.conf.template
- watcher.go
> Renamed watcher config to watch to be consistent

- compress.go
This pure-Go library (by yours truly) has optimized gzip/deflate function. At default compression levels this gives ~70% improvement in throughput for web content, as well as fewer allocations.
For performance comparisons see the package and https://blog.klauspost.com/gzip-performance-for-go-webservers/
I would love to give revel-specific benchmarks, but the benchmarks in "compress_test.go" appear broken, since it doesn't seem like compression is applied at all.
> Use improved deflate/gzip compressor.

- .travis.yml
- cache/cache_test.go
Add `sudo: false` to make travis-ci build faster. Please see [travis's doc](https://docs.travis-ci.com/user/workers/container-based-infrastructure/) about `sudo: false`.
> Add "sudo: false" to make travis-ci build faster

- .travis.yml
It takes long time for CI testing because of `sleep 30`. So I removed that and it looks fine.
What do you think?
[Related issue](https://github.com/revel/revel/issues/613)
> Remove sleep from .travis.yml

- revel.go
creates log's dir with any necessary parents, filemod is 0777
example in app config:
log.info.output  = log/%(app.name)s.log
> create the log directory if it does not already exist

- revel.go
- server.go
- skeleton/conf/app.conf.template
- util.go
This PR is fix and code improvements around #1055. Revel already has support for configuring log flags via `app.conf`, I have just set sensible default for it. How it will look like-
**`dev` mode:** (same as v0.12 release)
```bash
INFO  2016/05/25 18:22:50 revel.go:355: Loaded module static
INFO  2016/05/25 18:22:50 revel.go:355: Loaded module testrunner
INFO  2016/05/25 18:22:50 revel.go:220: Initialized Revel v0.13.0-dev (TBD) for >= go1.4
INFO  2016/05/25 18:22:50 run.go:57: Running logger (reveltest.com/logger) in dev mode
INFO  2016/05/25 18:22:50 harness.go:170: Listening on :9000
...
...
INFO  2016/05/25 18:22:57 main.go:30: Running revel server
Go to /@tests to run the tests.
Listening on :59681...
```
**`prod` mode:** (Improvement with sensible defaults for log flags)
```bash
... …
```
> logger fix and improvements

- i18n.go
- template.go
- util.go
- watcher.go
This adds a symlink-aware filepath.Walk helper to unify all the code which needs this functionality in revel.
It fixes #673 and an according pull request for revel/cmd is here: https://github.com/revel/cmd/pull/20.
I tested it with a new app, symlinked the whole folder into another directory (my original use-case) and symlinked some static files around. Everything worked as expected, revel still found all the files and the app built and ran fine.
> Add a symlink-aware filepath.Walk helper

- params.go
Its mainly explained in https://github.com/revel/revel/issues/503#issuecomment-65252825 - Excerpt below
The problem is that the order in which all the parameters of different types are appended is not documented and defined explicitly.
#503 has become possible because for Static.Serve(prefix, filepath string) only first prefix's value from c.Params is binded:
```
c.Params = url.Values {
"prefix": []url{"some_param_from_query", "public"},
}
```
Before #504 it was query parameter. Now it is a fixed parameter.
But we still should define what we are trying to get when we are appending parameters of different types both safe and unsafe ones together.
If it brings any value (and it looks like it does) we should better document the order (probably, we need to rethink and change it) and the fact …
> fix #1095 param map overwrite priority

- filterconfig.go
- revel.go
changes cookie.secure default to depend on HTTP SSL setting
should only be enabled when SSL is enabled in revel
also, fixes name of function in comment
> changes cookie.secure default to be based on HTTP SSL

- http.go
Based on the "extension" of the requested path, returns an appropriate content type
closes #963, #1045
> Based on the "extension" of the requested path, return content type

- i18n.go
Adds ability to specify a parameter to be used to set the locale. 
In revel config set the `i18n.locale.parameter` to the parameter name.
i18n.locale.parameter=locale
In routes specify the route path with the locale
GET  /hotels/:locale       Hotels.Index
> Adds the ability to set the language by a url parameter.

- results.go
The constants io.SeekEnd were not available at this time.
Used the numeric values instead
> Backwards compatibility to go1.6.

- controller.go
- router.go
Reverse routes was using the first controller in the route map for matching when determining the reverse route. This caused issues if the controller was partially defined in the route file. I modified the route check to validate against the MethodName as well
> Added method matching when doing a reverse route lookup

- router.go
Prevents an error about the route file is missing
> Checked for routes file existence before attempting to read

- cache/cache.go
- cache/inmemory.go
Modified inmemory functions to perform the changes robfig made.
Switched to version that robfig forked from
closes #993, #983
> Updated to patrickmn/go-cache, current robfig dependency was behind.

- validation.go
- validators.go
- validators_test.go
Added min max ranges for floats, modified base min max structure to be floats not ints
closes #760 
* revel/rfcs#1
* Breaking Change, Revel.Min, Revel.Max structs are now float64 not int
> Add new float validators

- http.go
- validation.go
- validation_test.go
You can invoke those functions within a model to attach a translated message to the ValidationError.Message object
The translator is taken from Revel.MessageFunc and is attached to the controller.Validation during the ValidationFilter process
closes #706
> Adds MessageKey ,ErrorKey to Validation object.

- before_after_filter.go
- controller.go
- controller_type.go
- fakeapp_test.go
Smart method application - controllers that have methods named `Before`,`After`,`Finally`,`Panic`, will be called in the same manner as the interceptor does. The method signature is a little different then normal to allow for method Overriding and cascades. ie if **Application** has **GorpController** controller embedded inside it and both define the `Before` method then what happens is the `GorpController.Before` is invoked before the `Application.Before`. The method signature must match the following syntax though 
```
func (c Application) Before() (r revel.Result, a Application) {
...
func (c *GorpController) Before() (result revel.Result, controller *GorpController) {
```
So notice along with the revel.Result we return the Controller type ? This is so when the application starts up it …
> Before, after, panic, finally controller auto rule implementation

- binder.go
- binder_test.go
Replacement for PR that was not able to be merged #998
closes #997, #998
Updates the route tests to fix failing tests
> Allow binder to bind struct map (replacement for pr 998)

- .codebeatsettings
- controller.go
- logger/handlers.go
- logger/utils.go
- panic.go
- results.go
- template.go
This PR returns the output of a rendered template. Useful for Json responses. Example application
```
html,err := c.TemplateOutput("Response/jsonTemplate.html")
if err!=nil {
return c.RenderJSON(map[string]interface{}{"error": err.Error(), "success": false})
}
return c.RenderJSON(map[string]interface{}{"html": string(html), "success": true})
```
Added `controller.TemplateOut`, `revel.TemplateOutArgs` `controller.TemplateOut` uses the ViewArgs to pass to the template, `revel.TemplateOutArgs` requires both the template path and the args. Both source the template from revel.MainTemplate
> Added template read and population

- controller.go
- http.go
- intercept.go
- intercept_test.go
- module.go
- results.go
- router.go
- template.go
Added args to be passed to action using the Controller.Redirect
Added namespace to resolved path
Renamed ServerHeader to Header (more backwards compatible)
Updated intercept module to sort intercepts by "depth" this ensures that the most embedded intercept gets called first
Added "appModule" to revel.Modules
Added additional logging in router.splitactionpath
Added setting template initialization engines to be read from template.engines
> Prerelease patche set

- server_adapter_go.go
Modified code to attempt to write if stream read from is not an io.ReadSeeker
closes #1261
> Server adapter bug

- server_adapter_go.go
The Message codec can only handle strings and byte slices. Since the method is called JSON, let's call the JSON codec underneath.
>  Fix JSON to struct deserialization

- controller.go
I was rewriting my Golang web-application where I serve images (listed in my database) from disk, I was repeating myself with the `os.Open()` and though by myself, why isn't this part of the framework. I think this is a good addition to have even more batteries included. :-)
Greetings,
Rik
> Render a file by a provided filepath

- results.go
Sometimes a ContentDisposition is not what is desired, for example if a user needs a file served with a custom name via `RenderFile()`, the Name cannot be altered. Allowing to omit the `Content-Disposition` header gives the user the opportunity to do it themselves.
Greetings,
Rik
PS, I see that my editor (VS Code) cleaned up the code and added some missing spaces, I hope this is not a problem for you?
> Allow ContentDisposition to become empty

- cache/cache_test.go
- router.go
- router_test.go
I Added Webdav and Cache Methods to router.go(routePattern)
*Currently, Revel only supports method are below*
```go
GETPOST|PUT|DELETE|PATCH|OPTIONS|HEAD|WS
```
*API server need to additional methods, The following is new methods*
```
PROPFIND	
MKCOL		
COPY		
MOVE		
PROPPATCH	
LOCK		
UNLOCK		
TRACE		
PURGE		
```
Cheers.
> add WebDav and Cache Method (PURGE)

- field.go
In order to created form field template, hope the option list can be included in Field structure and can be used in format as below
```html
{{with $field := field "record.Status"}}
{{template "fieldTemplate/radio.html" $field}}
{{end}}
```
in radio.html template 
```html
{{.Name}}
{{range .Options }}
{{.}}
{{end}}
```
The option list can be set as the way set field value (which using flash). Options, use ViewArgs["options"]. 
```go
c.ViewArgs["options"] = map[string][]string{
"record.Status": map[string][]string{"Started","Ongoing", "Finished"},
}
```
> added Options method in Field

- watcher.go
@https://github.com/go-fsnotify/fsnotify/issues/1
@https://github.com/revel/revel/issues/1323
> Fix import to point to the fsnotify/fsnotify.v1.

- watcher.go
Due to the vulnerability discussed in  https://github.com/go-fsnotify/fsnotify/issues/1, this patch corrects the import path for fsnotify.
> Updates fsnotify import path due to import path vulnerability

- template_engine.go
When I use command "revel version" to check the revel's version, I saw a bug there, and the below is the screenshot.
I have reviewed the code, and find in line 45 of "template_engine.go" have something wrong.
`templateLog.Debug("Registered template engine loaded", key)`
according to the log15, we missed one parameter. and I change it to
`templateLog.Debug("Registered template engine loaded", "name", key)`
Please check is it right, thanks!
> fix template_engine.go's DEBUG bug of command "revel version";

- event.go
- event_test.go
- fakeapp_test.go
- filter.go
- module.go
- revel.go
- router.go
- server-engine.go
- server.go
- server_adapter_go.go
- template.go
- template_adapter_go.go
- template_engine.go
Modified handler to be func(typeOf revel.Event, value interface{}) (responseOf revel.EventResponse)
Broke out event sending and constants into their own class
> Updated revel internal event handling system so external users can raise the events manually

- .travis.yml
- event.go
- fakeapp_test.go
- logger/composite_multihandler.go
- logger/doc.go
- logger/handlers.go
- logger/init.go
- logger/init_test.go
- logger/log_function_map.go
- logger/logger.go
- logger/revel_logger.go
- logger/terminal_format.go
- logger/utils.go
- logger/wrap_handlers.go
- results.go
- revel_hooks.go
- server-engine.go
- server.go
- server_adapter_go.go
- server_test.go
- template.go
- template_adapter_go.go
- util.go
Updated test cases
Updated shutdown to support windows environment
Patched shutdown support to make it work through the event engine
Added ENGINE_SHUTDOWN_REQUEST to events, raising this event will cause the server to shutdown
Assigned Server engines to receive revel.Events
Added revel.OnAppStop hooks - breaking change, was revel.OnAppShutdown
Removed revel.OnAppShutdown
Normalized startup / shutdown hooks into their own package
> Shutdown update

- cache/redis.go
- module.go
- template_functions.go
Fixed the spelling errors found by misspell in [Go Report](https://goreportcard.com/report/github.com/revel/revel#misspell)
> Fix spelling errors from go report

- controller.go
- model/revel_container.go
- revel.go
- server-engine.go
- server.go
- server_adapter_go.go
- utils/simplestack.go
- utils/simplestack_test.go
Moved SimpleStack into utils folder
Added RevelContainer
Moved controller stacks inside revelcontainer
Added option to not reuse controllers via `revel.controller.reuse`
> Bug fix, not reuse controllers

- before_after_filter.go
- before_after_filter_test.go
Adjusts the `BeforeAfterFilter` so that it doesn't continue to execute interceptors or actions if the BEFORE function returns a value.
Adds a new test file, `before_after_filter_test.go`, which verifies this behaviour.
Fixes #1433.
> Fix bug where action is invoked even when Before interceptor returns non-nil value

- session/session.go
Looks like it was added for debugging and never removed, now it only creates noise in logs.
> Remove a stray println call.

- validators.go
- validators_test.go
- Fix (#1458) the undetected self-closing tags in isPureTextStrict
- Fix (#1457) the always uses STRICT mode in PureText.IsSatisFied
- refer : 
- https://github.com/revel/revel/pull/1459
- https://github.com/revel/revel/pull/1461
- https://github.com/revel/revel/issues/1460
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/revel/revel/1462)
> Fix the Undetected self-closing tags in isPureTextStrict and always uses STRICT mode in PureText.IsSatisFied

- flash.go
- revel.go
- session_adapter_cookie.go
- validation.go
Support SameSite cookie parameter
This has become an issue when developing locally, because most browsers now give warnings if you don't have SameSite set, and the warning states they will soon ban cookies that don't have SameSite or Secure set. So this would allow you to set SameSite so it'll work when developing locally over HTTP not HTTPS.
I'm not sure, but maybe it should default to 'strict' for local development so people don't get stung by this when browsers begin to enforce this rule; it seems like it'd be safer to leave this as 'default' for production so as to not break anyone's sites - however it might even better to default it to 'strict' for production for new sites too? Open to the maintainers thoughts on those issues.
Thanks all
> SameSite cookie support

- cache/redis.go
The package github.com/garyburd/redigo doesn't exist anymore.
Just replaced the import by the new package : https://github.com/gomodule/redigo/
> Correction garyburd/redigo import

- binder.go
Hi, this one-line PR fixes a problem when binding to a pointer type and the bind fails. At the moment it tries to set to an incompatible type. Here's example code:
```
var threshold float64
var pThreshold *float64
c.Params.Bind(&pThreshold, "threshold")
if pThreshold != nil {
threshold = *pThreshold
}
if pThreshold == nil || threshold < 0.0 || threshold > 1.0 {
_, threshold, err = selectedModel.GetDefaultThreshold()
}
if err != nil {
return c.RenderError(err)
}
```
If the param is something that isn't convertible into a float, the return value of the `Bind` call in `binder.go:160` isn't `CanAddr()`, and it tries to return the value itself, instead of a pointer. But because it is a pointer binder, it is *supposed* to return a pointer. Returning something else will cause it to crash with …
> Fix a bug when binding to pointer
