server.go
=> Fixes template loading order whether watcher is enabled or not

server.go
Regression from #844 
@anonx Everything looks good now, but a quick sanity check of the last few commits would be great.
=> Fixes regression bug that caused templates not to trigger hot reload

revel.go, version.go, version.yaml
=> Adds first draft of a version file to Revel

panic.go
=> Only shows debug stack details in DevMode

revel.go, session.go, skeleton/conf/app.conf.template, validation.go
#770
@pedromorgan Feedback on the `app.conf` addition would be nice. Thanks!
=> Adds cookie domain support

template.go
PR to discuss wording of error message, but otherwise addresses #811
=> Friendly URL template errors

router.go
ensure routes are loaded before returning. #883
=> ensure routes are loaded before returning from OnAppStart callback

compress.go
=> Change compression handling

testing/testsuite.go
=> PutForm test helper

server.go, server_test.go
Add Order To onAppStart.
With This change we can order to run function in runStartupHooks.
=> Add Order to OnAppStart

skeleton/conf/app.conf.template
Docs for revel/revel#153
@revel/core take a peak. It's an easy merge, but I want the team to work together.
Could this PR be improved?
=> Documents watch.gopath per revel/revel#153

server.go
Fix change Server.Addr in the hook function and it does not work.
Why change Server.Addr?
I hope read port from another config file, the config file is will modified by user and don't override while reinstall or update my software.
=>  Fix change Server.Addr in the hook function and it does not work.

i18n.go
This patch searches the modules for message files as well. This enhances modules so they can also provide translations with the packages.
=> Search modules for message files as well

skeleton/conf/app.conf.template
=> Fix skeleton config to match code and doc. #878

controller.go, server.go
=> Added a client ip into controller instance

errors.go
Addresses issue #273.
_Replaces #1081 which was against the wrong branch._
=> Less aggressive trimming of stack traces

filterconfig.go
=> fix FilterController example

.travis.yml, errors.go
Changed samples to example to match repository
=> Changed samples to example to match repository

CONTRIBUTING.md
Updated Command:
`git checkout -b feature/useful-new-thing origin/develop`
Current command : 
`git checkout -b feature/useful-new-thing develop`
Problem:
This tries to find the local branch develop which instead should use the remote branch origin/develop.
Updated Command:
`git push fork feature/useful-new-thing`
Current command:
`git push fork develop`
Problem:
This tries to push the changes to the branch develop instead of the feature branch.
=> Minor fixes to the contribution guide

binder.go, binder_test.go, params.go, validation.go
Automatic JSON binding to struct in parameters, also changed validation to not store validation state via a cookie, since with a json request/response no redirect is required and therefor no persistent data is required.
Also renamed local variable error to err so no package conflict error will occur
=> JSON Parameter binding

controller.go, i18n.go, results.go, revel.go, template.go, template_adapter_go.go, template_engine.go
=> Changes to revel to support a template engine architecture

validation.go, validators.go, validators_test.go
Hi, I Just made validation methods below
- IPAddr : Validation for IP Address format including IPv4 , IPv6 , IPv4-mapped IPv6 with CIDR
- MacAddr : Validation for H/W MAC Address
- Domain : Validation for Domain (Hostname)
- URL : Validation for URL
- PureText : Validation for sanitary string
- FilePath : Validation for File Path
thx
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/revel/revel/1114)
=> Improve Validation API

README.md, version.go
Update version tags on develop branch
=> Update version tags on develop branch 

template_adapter_go.go
Fixes template delimiters issue
closes #1199
=> Fixes template delimiters issue

template.go
The template map was being written to by multiple threads, this fixes that issue
closes #1188
=> Concurrent template writes

README.md, http.go, router.go, server-engine.go, server_adapter_go.go
Added fixed parameters addition on Reverse call
Added Go report card to readme
Removed deprecation from Request.URL
=> Some small bug fixes / improvements

template_functions.go
Added new template function (Go) called "timeago" using https://github.com/xeonx/timeago
Documentation added to the website.
If the PR is accepted, consider the documentation https://github.com/revel/revel.github.io/pull/133.
=> Timeago Template Func

template.go, template_engine.go
fix https://github.com/revel/revel/issues/1188
=> Fix for the template map concurrency issue

binder.go, module.go, router.go
Logged as error for json unmarshal error
Changed module filepath match to use filepath library
Assigned typeOfController when controller match requested
=> Prerelease findings

controller.go
add HTTPCode() for Controller.RenderError()
=> add HTTPCode() for Controller.RenderError()

logger.go, module.go, revel.go
Added code to make vendoring work
=> Vendoring fixes

.travis.yml, compress.go, errors.go, http.go, logger/format.go, logger/utils.go, module.go, panic.go, server_adapter_go.go
Fix websocket issue
Modified errors if source file is not found it will not fail
Modified panic if in DevMode a nicely formatted stack is printed.
closes #1267, #1276, #1279
=> Production patchset

http.go
=> Fix error propagation

.travis.yml, module.go, namespace.go, panic.go, results.go, template.go, template_engine.go
Normalize filepath.ToSlash the filepaths in the module
closes #1294
Fix panic handler to prevent nil errors from causing a panic
Some cleanup of comments renaming of namespace to LOCAL
=> Production patchset 2

logger/handlers.go
fix color is disabled on the windows
=> fix color is disabled on the windows

binder.go
=> add custom timezone support

results.go
=> Remove unnecessary log output in results.go

.travis.yml, README.md, controller_type.go, logger.go, logger/utils.go, revel.go, server.go, server_adapter_go.go, template.go, template_adapter_go.go, watcher.go
Updated watcher to run refresh in parallel
Updated travis Minimum version to 1.8
Added ability to send some JSON code into the "mode" for Revel, this allows for tweaking the logging for tests and could be used elsewhere
=> Little fixes

http.go, revel.go, server-engine.go, server.go, server_adapter_go.go, testing/testsuite.go
Added hard fail REVEL_FAILURE event
Added HTTP_REQUEST_CONTEXT fetch
Breaking change function
`Request.Context() map[string]interface()` renamed to
`Request.Args() map[string]interface()`
new function added
`Request.Context() context.Context`
=> Added some features

.travis.yml, logger/composite_multihandler.go, logger/doc.go, logger/handlers.go, logger/init.go, logger/init_test.go, logger/log_function_map.go, logger/logger.go, logger/revel_logger.go, logger/terminal_format.go, logger/utils.go, logger/wrap_handlers.go
Further isolated dependencies on log 15 to just the revel_logger package
All handlers are declared locally
Added test cases
Fixed bugs
Documented rules
=> Logger enhancements

.travis.yml, logger/composite_multihandler.go, logger/doc.go, logger/handlers.go, logger/init.go, logger/init_test.go, logger/log_function_map.go, logger/logger.go, logger/revel_logger.go, logger/terminal_format.go, logger/utils.go, logger/wrap_handlers.go, results.go, template.go, template_adapter_go.go
The template was not displaying the source code when an error occurred this fixes that
=> Fixed template bug

.travis.yml, controller.go, fakeapp_test.go, i18n_test.go, logger.go, revel.go, server.go, session_adapter_cookie.go
Updated travis allowed windows failures
=> Updated travis for windows build

compress.go, server-engine.go, server_adapter_go.go
=> Added getKeys() for the header

module.go
=> Change stack import to fix issue #1482

revel.go, watcher.go
Updated watcher to use master branch
=> Updated revel to receive paths passed in

conf/mime-types.conf
added "wasm=application/wasm" in conf/mime-types.conf.
=> added wasm mime-type

README.md
=> Corrects install command for new version of go

validators.go
Fixing typo "vaild" into "valid".
=> fixing typos

compress.go
To resolve following issue: 
https://github.com/revel/revel/issues/1519
=> Adding a MIME type for compressableMimes

logger/handlers.go
There was a recusive loop in the logger, this fixes it
closes #1542
=> Fixed log recursive call
